import { apiClient } from './api-client.js';
import { addPackageRequest } from './package-quote-adapter.js';
import { loadQuoteState, persistQuoteState } from './quote-state.js';

(function(){
  'use strict';
  const WHATSAPP='263779680336';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=(v,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(v);
  const image=path=>/^https?:\/\//i.test(path)||String(path).startsWith('/')?path:'../'+path;
  const wa=message=>'https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent(message);
  let pkg,packages=[];
  function list(items,className=''){return `<ul class="page-list ${className}">${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`;}
  function duration(){return `<span class="hero-fact" data-package-field="duration">${esc(pkg.duration.label)}</span>`;}
  function pricePanel(){return `<header class="price-panel"><p>${pkg.priceOnRequest?'<strong>Price on request</strong>':`From <strong>${money(pkg.priceFrom,pkg.currency)}</strong><small>${esc(pkg.priceUnit)} · ${esc(pkg.duration.label)}</small>`}</p><p class="price-note">Availability and final cost are confirmed in your quotation.</p></header>`;}
  function gallery(){const items=pkg.gallery?.length?pkg.gallery:[pkg.image];return `<section class="content-block package-gallery-block" aria-labelledby="galleryTitle" data-package-component="gallery"><h2 id="galleryTitle">A closer look</h2><div class="page-gallery">${items.map((src,index)=>`<figure><img src="${image(src)}" width="1536" height="1024" loading="${index?'lazy':'eager'}" decoding="async" alt="${esc(pkg.galleryAlts?.[index]||pkg.imageAlt||pkg.name)}">${pkg.galleryCaptions?.[index]?`<figcaption>${esc(pkg.galleryCaptions[index])}</figcaption>`:''}</figure>`).join('')}</div></section>`;}
  function cta(){return `<div class="detail-actions"><button class="detail-button gold" type="submit">${esc(pkg.callToAction?.label||'Build My Quote')}</button><button class="detail-button outline" id="addDetailTrip" type="button">Add to My Trip</button><a class="detail-button whatsapp" id="detailWhatsApp" href="${wa('Hello Virtcruise Travels, I would like to enquire about '+pkg.name+'.')}" target="_blank" rel="noopener noreferrer">Enquire on WhatsApp</a></div>`;}
  function metadata(){const title=pkg.seo?.title||pkg.name+' | Virtcruise Travels',description=pkg.seo?.description||pkg.summary,canonical=pkg.seo?.canonical||`https://www.virtcruisetravels.com/packages/${pkg.slug}.html`,cover=image(pkg.image);document.title=title;const set=(selector,value,attribute='content')=>{const node=$(selector);if(node&&value)node.setAttribute(attribute,value);};set('meta[name="description"]',description);set('link[rel="canonical"]',canonical,'href');set('meta[property="og:title"]',pkg.seo?.openGraphTitle||title);set('meta[property="og:description"]',pkg.seo?.openGraphDescription||description);set('meta[property="og:url"]',canonical);set('meta[property="og:image"]',cover);set('meta[property="og:image:alt"]',pkg.imageAlt);let structured=$('#packageStructuredData');if(!structured){structured=document.createElement('script');structured.type='application/ld+json';structured.id='packageStructuredData';document.head.append(structured);}structured.textContent=JSON.stringify({'@context':'https://schema.org','@type':'TouristTrip',name:pkg.name,description:pkg.description||pkg.summary,url:canonical,image:cover,touristType:pkg.packageType,duration:`P${pkg.duration.days}D`});}
  function render(){
    metadata();
    $('#packagePageHero').innerHTML=`<img src="${image(pkg.image)}" width="1536" height="1024" fetchpriority="high" alt="${esc(pkg.imageAlt||pkg.name+' in '+pkg.destination)}"><div class="package-hero-copy" data-package-component="summary"><p class="eyebrow">${esc(pkg.destination)}</p><h1 data-package-field="name">${esc(pkg.name)}</h1><p data-package-field="summary">${esc(pkg.summary)}</p><div class="hero-facts">${duration()}<span class="hero-fact">From ${money(pkg.priceFrom,pkg.currency)}</span></div></div>`;
    const highlights=pkg.highlights?.length?`<section class="content-block"><h2>Highlights</h2>${list(pkg.highlights)}</section>`:'';const lists=(pkg.inclusions?.length||pkg.exclusions?.length)?`<section class="content-block two-column-lists" aria-label="Package inclusions and exclusions"><div class="info-card"><h2>What’s included</h2>${list(pkg.inclusions||[])}</div><div class="info-card"><h2>What’s not included</h2>${list(pkg.exclusions||[],'exclusions')}</div></section>`:'';
    $('#packagePageMain').innerHTML=`${gallery()}<div class="page-grid"><div><section class="content-block"><h2>About this package</h2><p>${esc(pkg.description||pkg.summary)}</p></section>${highlights}${lists}</div><aside aria-label="Package enquiry"><div class="enquiry-card">${pricePanel()}<form class="detail-form" id="detailEnquiryForm"><h2>Plan this trip</h2><div class="detail-form-grid"><label>Your name<input name="name" autocomplete="name" required></label><label>Mobile number<input name="mobile" type="tel" autocomplete="tel" required></label><label>Preferred travel date<input name="departure" type="date"></label><label>Travellers<select name="travellers"><option value="1">1 traveller</option><option value="2">2 travellers</option><option value="3">3 travellers</option><option value="4">4 travellers</option><option value="5">5+ travellers</option></select></label></div>${pkg.optionalExtras?.length?`<fieldset class="extras-checklist"><legend>Optional add-ons</legend>${pkg.optionalExtras.map(extra=>`<label><input type="checkbox" name="extra" value="${esc(extra.id)}"> <span>${esc(extra.name)} · ${extra.price==null?'Quote required':money(extra.price,extra.currency)}</span></label>`).join('')}</fieldset>`:''}${cta()}</form></div></aside></div><section class="related-packages"><h2>Continue exploring</h2><div class="related-grid">${relatedMarkup()}</div></section>`;
    bind();
  }
  function relatedMarkup(){return packages.filter(item=>item.id!==pkg.id&&item.packageType!=='TRIP_ADD_ON').slice(0,3).map(item=>`<article class="related-card"><img src="${image(item.image)}" width="960" height="640" loading="lazy" decoding="async" alt="${esc(item.imageAlt||item.name)}"><div><h3>${esc(item.name)}</h3><p>${esc(item.destination)} · ${item.priceOnRequest?'Price on request':'From '+money(item.priceFrom,item.currency)}</p><a href="${item.slug}.html">View package</a></div></article>`).join('');}
  function selectedExtras(){return $$('input[name=extra]:checked').map(input=>input.value);}
  function addToTrip(continueToBuilder=false){const state=loadQuoteState(),form=$('#detailEnquiryForm'),data=new FormData(form),selectedAddOns=selectedExtras(),result=addPackageRequest(state,pkg,{source:'package-page',selectedAddOns});const request=result.request,travellers=Number(data.get('travellers')||1);request.details.departureDate=data.get('departure')||request.details.departureDate||'';request.details.travellers=travellers;request.details.adults=travellers;request.details.selectedAddOns=selectedAddOns;state.destination||=pkg.destination;state.customer.fullName||=data.get('name')||'';state.customer.mobile||=data.get('mobile')||'';try{persistQuoteState(state);showToast(result.status==='added'?pkg.name+' added to My Trip':pkg.name+' updated in My Trip');}catch(error){console.error('Virtcruise package draft could not be persisted:',error);showToast('Trip updated, but it may not survive a refresh.');}if(continueToBuilder)location.href='../index.html#cart';}
  function message(){const form=$('#detailEnquiryForm'),data=new FormData(form),extras=selectedExtras().map(id=>pkg.optionalExtras.find(extra=>extra.id===id)).filter(Boolean);return ['Hello Virtcruise Travels, I would like a package quotation.','Package: '+pkg.name,'Destination: '+pkg.destination,'Name: '+(data.get('name')||'Not provided'),'Mobile: '+(data.get('mobile')||'Not provided'),'Travel date: '+(data.get('departure')||'Flexible'),'Travellers: '+data.get('travellers'),'Optional extras: '+(extras.length?extras.map(extra=>extra.name).join(', '):'None selected'),'Please confirm availability and the final price.'].join('\n');}
  function showToast(text){const toast=$('#detailToast');toast.textContent=text;toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),2200);}
  function bind(){$('#addDetailTrip').addEventListener('click',()=>addToTrip(false));$('#detailEnquiryForm').addEventListener('submit',event=>{event.preventDefault();if(event.currentTarget.reportValidity())addToTrip(true);});$('#detailWhatsApp').addEventListener('click',event=>event.currentTarget.href=wa(message()));}
  async function init(){try{[packages,pkg]=await Promise.all([apiClient.packages.list(),apiClient.packages.getBySlug(document.body.dataset.packageSlug)]);if(!pkg)throw new Error('Package not found');render();}catch(error){$('#packagePageHero').innerHTML='';$('#packagePageMain').innerHTML=`<div class="package-error" role="alert"><h1>${error?.status===404?'Package not found':'Package details are unavailable'}</h1><p>Check your connection and try again, or return to all packages.</p><a href="../index.html#allPackages">Explore all packages</a></div>`;}}
  document.addEventListener('DOMContentLoaded',init);
})();
