import { apiClient } from './api-client.js';
import { addPackageRequest } from './package-quote-adapter.js';
import { loadQuoteState, persistQuoteState } from './quote-state.js';

(function(){
  'use strict';
  const WHATSAPP='263779680336';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=(v,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(v);
  const image=path=>'../'+path;
  const wa=message=>'https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent(message);
  let pkg,packages=[];
  function list(items,className=''){return `<ul class="page-list ${className}">${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`;}
  function duration(){return `<span class="hero-fact" data-package-field="duration">${esc(pkg.duration.label)}</span>`;}
  function pricePanel(){return `<header class="price-panel"><p>From <strong>${money(pkg.priceFrom,pkg.currency)}</strong><small>${esc(pkg.priceUnit)} · ${esc(pkg.duration.label)}</small></p><p class="price-note">Indicative price; availability and final cost are confirmed in your quotation.</p></header>`;}
  function gallery(){return `<section class="content-block package-gallery-block" aria-labelledby="galleryTitle" data-package-component="gallery"><h2 id="galleryTitle">A closer look</h2><div class="page-gallery">${pkg.gallery.map((src,index)=>`<figure><img src="${image(src)}" width="1536" height="1024" loading="${index?'lazy':'eager'}" decoding="async" alt="${esc(pkg.galleryAlts?.[index]||pkg.imageAlt||pkg.name)}"><figcaption>${esc(pkg.galleryAlts?.[index]||pkg.destination)}</figcaption></figure>`).join('')}</div></section>`;}
  function cta(){return `<div class="detail-actions"><button class="detail-button gold" type="submit">Build My Quote</button><button class="detail-button outline" id="addDetailTrip" type="button">Add to My Trip</button><a class="detail-button whatsapp" id="detailWhatsApp" href="${wa('Hello Virtcruise Travels, I would like to enquire about '+pkg.name+'.')}" target="_blank" rel="noopener noreferrer">Enquire on WhatsApp</a></div>`;}
  function render(){
    document.title=pkg.name+' | Virtcruise Travels';
    $('#packagePageHero').innerHTML=`<img src="${image(pkg.image)}" width="1536" height="1024" fetchpriority="high" alt="${esc(pkg.imageAlt||pkg.name+' in '+pkg.destination)}"><div class="package-hero-copy" data-package-component="summary"><p class="eyebrow">${esc(pkg.destination)}</p><h1 data-package-field="name">${esc(pkg.name)}</h1><p data-package-field="summary">${esc(pkg.summary)}</p><div class="hero-facts">${duration()}<span class="hero-fact">From ${money(pkg.priceFrom,pkg.currency)}</span></div></div>`;
    $('#packagePageMain').innerHTML=`${gallery()}<div class="page-grid"><div><section class="content-block two-column-lists" aria-label="Package inclusions and exclusions"><div class="info-card"><h2>What’s included</h2>${list(pkg.inclusions)}</div><div class="info-card"><h2>What’s not included</h2>${list(pkg.exclusions,'exclusions')}</div></section><section class="content-block"><h2>Your itinerary</h2><div class="page-itinerary">${pkg.itinerary.map(item=>`<article><h3><span>${esc(item.day)}</span> · ${esc(item.title)}</h3><p>${esc(item.description)}</p></article>`).join('')}</div></section><section class="content-block"><h2>Booking terms</h2>${list(pkg.bookingTerms,'terms-list')}</section><section class="content-block"><h2>Frequently asked questions</h2><div class="faq-list">${pkg.faq.map(item=>`<details><summary>${esc(item.question)}</summary><p>${esc(item.answer)}</p></details>`).join('')}</div></section></div><aside aria-label="Package enquiry"><div class="enquiry-card">${pricePanel()}<form class="detail-form" id="detailEnquiryForm"><h2>Plan this trip</h2><div class="detail-form-grid"><label>Your name<input name="name" autocomplete="name" required></label><label>Mobile number<input name="mobile" type="tel" autocomplete="tel" required></label><label>Preferred travel date<input name="departure" type="date"></label><label>Travellers<select name="travellers"><option value="1">1 traveller</option><option value="2">2 travellers</option><option value="3">3 travellers</option><option value="4">4 travellers</option><option value="5">5+ travellers</option></select></label></div><fieldset class="extras-checklist"><legend>Optional add-ons</legend>${pkg.optionalExtras.map(extra=>`<label><input type="checkbox" name="extra" value="${extra.id}"> <span>${esc(extra.name)} · ${extra.price==null?'Quote required':money(extra.price,extra.currency)}</span></label>`).join('')}</fieldset>${cta()}</form></div></aside></div><section class="related-packages"><h2>Continue exploring</h2><div class="related-grid">${relatedMarkup()}</div></section>`;
    bind();
  }
  function relatedMarkup(){const candidates=packages.filter(item=>item.id!==pkg.id).sort((a,b)=>Number(b.categories.some(category=>pkg.categories.includes(category)))-Number(a.categories.some(category=>pkg.categories.includes(category))));return candidates.slice(0,3).map(item=>`<article class="related-card"><img src="${image(item.image)}" width="960" height="640" loading="lazy" decoding="async" alt="${esc(item.imageAlt||item.name)}"><div><h3>${esc(item.name)}</h3><p>${esc(item.destination)} · From ${money(item.priceFrom,item.currency)}</p><a href="${item.slug}.html">View package</a></div></article>`).join('');}
  function selectedExtras(){return $$('input[name=extra]:checked').map(input=>input.value);}
  function addToTrip(continueToBuilder=false){const state=loadQuoteState(),form=$('#detailEnquiryForm'),data=new FormData(form),selectedAddOns=selectedExtras(),result=addPackageRequest(state,pkg,{source:'package-page',selectedAddOns});const request=result.request,travellers=Number(data.get('travellers')||1);request.details.departureDate=data.get('departure')||request.details.departureDate||'';request.details.travellers=travellers;request.details.adults=travellers;request.details.selectedAddOns=selectedAddOns;state.destination||=pkg.destination;state.customer.fullName||=data.get('name')||'';state.customer.mobile||=data.get('mobile')||'';try{persistQuoteState(state);showToast(result.status==='added'?pkg.name+' added to My Trip':pkg.name+' updated in My Trip');}catch(error){console.error('Virtcruise package draft could not be persisted:',error);showToast('Trip updated, but it may not survive a refresh.');}if(continueToBuilder)location.href='../index.html#cart';}
  function message(){const form=$('#detailEnquiryForm'),data=new FormData(form),extras=selectedExtras().map(id=>pkg.optionalExtras.find(extra=>extra.id===id)).filter(Boolean);const known=pkg.priceFrom+extras.reduce((sum,extra)=>sum+(extra.price||0),0);return ['Hello Virtcruise Travels, I would like a package quotation.','Package: '+pkg.name,'Destination: '+pkg.destination,'Name: '+(data.get('name')||'Not provided'),'Mobile: '+(data.get('mobile')||'Not provided'),'Travel date: '+(data.get('departure')||'Flexible'),'Travellers: '+data.get('travellers'),'Optional extras: '+(extras.length?extras.map(extra=>extra.name).join(', '):'None selected'),'Estimated known price from: '+money(known,pkg.currency)+' per traveller','Please confirm availability and the final price.'].join('\n');}
  function showToast(text){const toast=$('#detailToast');toast.textContent=text;toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),2200);}
  function bind(){$('#addDetailTrip').addEventListener('click',()=>addToTrip(false));$('#detailEnquiryForm').addEventListener('submit',event=>{event.preventDefault();if(event.currentTarget.reportValidity())addToTrip(true);});$('#detailWhatsApp').addEventListener('click',event=>event.currentTarget.href=wa(message()));}
  async function init(){try{packages=await apiClient.packages.list();pkg=await apiClient.packages.getBySlug(document.body.dataset.packageSlug);if(!pkg)throw new Error('Package not found');render();}catch(error){console.error(error);$('#packagePageMain').innerHTML='<div class="package-error" role="alert"><h1>Package details are unavailable</h1><p>Check your connection and try again, or return to all packages.</p><a href="../index.html#allPackages">Explore all packages</a></div>';}}
  document.addEventListener('DOMContentLoaded',init);
})();
