import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright-core';

const enabled = process.env.RUN_CUSTOMER_BANK_TRANSFER_REAL_ACCEPTANCE === 'true';
const web = process.env.BANK_TRANSFER_ACCEPTANCE_WEB || 'http://localhost:15003';
const api = process.env.BANK_TRANSFER_ACCEPTANCE_API || 'http://localhost:8080';
const localKey = process.env.LOCAL_AUTH_TEST_KEY || '';
const dbEnv = {...process.env,PGHOST:'127.0.0.1',PGPORT:'55436',PGDATABASE:'vc_g1a',PGUSER:'vc_g1a',PGPASSWORD:'vc_g1a_disposable'};
const password = 'Acceptance-Only-2026!';
const run = `g1a-${Date.now()}`;
const email = name => `${run}-${name}@test.invalid`;
const sql = statement => execFileSync('psql',['-v','ON_ERROR_STOP=1','-At','-F','|','-c',statement],{env:dbEnv,encoding:'utf8'}).trim();
const eventually = async (action, timeout=15000) => { const until=Date.now()+timeout; let last; while(Date.now()<until){try{return await action();}catch(error){last=error;await new Promise(resolve=>setTimeout(resolve,250));}}throw last; };
async function json(path,{token,method='GET',body,key}={}){const response=await fetch(`${api}${path}`,{method,headers:{Accept:'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...(body?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined});return {response,data:(await response.json().catch(()=>null))?.data};}
async function browserRegisterAndVerify(page,address,name){await page.goto(`${web}/register/?api=local`);await page.getByLabel('First name').fill(name);await page.getByLabel('Last name').fill('Acceptance');await page.getByLabel('Email').fill(address);await page.locator('#password').fill(password);await page.locator('#confirmPassword').fill(password);await page.getByLabel(/terms/i).check();await page.getByLabel(/privacy/i).check();await page.getByRole('button',{name:/create account/i}).click();await page.getByText(/check your email/i).waitFor();const url=new URL('/api/v1/auth/development/token',api);url.searchParams.set('email',address);url.searchParams.set('purpose','VERIFICATION');const tokenResponse=await fetch(url,{headers:{'X-Local-Test-Key':localKey}});assert.equal(tokenResponse.status,200);const token=(await tokenResponse.json()).data.token;await page.goto(`${web}/verify-email/?api=local&token=${encodeURIComponent(token)}`);await page.getByText(/verified|verification complete/i).waitFor();}
async function browserLogin(page,address){await page.goto(`${web}/signin/?api=local`);await page.getByLabel('Email address').fill(address);await page.locator('#password').fill(password);await Promise.all([page.waitForURL(/\/(?:account|dashboard)\//),page.getByRole('button',{name:/sign in/i}).click()]);}
async function apiLogin(address){const result=await json('/api/v1/auth/login',{method:'POST',body:{email:address,password,deviceName:'DEV-005G1A'}});assert.equal(result.response.status,200);return result.data;}

test('complete real customer bank-transfer journey',{skip:!enabled,timeout:180000},async()=>{
  assert.ok(localKey.length>=24);
  assert.equal(sql("select current_setting('server_version'),current_setting('server_encoding'),current_setting('TimeZone'),current_setting('password_encryption')"),'18.4|UTF8|UTC|scram-sha-256');
  assert.equal(sql("select string_agg(version,',' order by installed_rank) from flyway_schema_history where success"),'1,2,3,4,5,6,7,8,9,10,11,12');
  const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
  const customerEmail=email('customer-a'),otherEmail=email('customer-b'),financeEmail=email('finance'),consultantEmail=email('consultant'),adminEmail=email('admin');
  const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'});const page=await context.newPage();
  try{
    await browserRegisterAndVerify(page,customerEmail,'Customer');
    for(const [address,name] of [[otherEmail,'Other'],[financeEmail,'Finance'],[consultantEmail,'Consultant'],[adminEmail,'Admin']]){const p=await browser.newPage();await browserRegisterAndVerify(p,address,name);await p.close();}
    sql(`${[['finance','ROLE_FINANCE'],['consultant','ROLE_CONSULTANT'],['admin','ROLE_ADMIN']].map(([name,role])=>`delete from user_roles where user_account_id=(select id from user_accounts where normalized_email='${email(name)}'); insert into user_roles(user_account_id,role_id) select u.id,r.id from user_accounts u cross join roles r where u.normalized_email='${email(name)}' and r.name='${role}'; update user_accounts set account_type='STAFF',customer_id=null where normalized_email='${email(name)}';`).join(' ')}`);
    const customerId=sql(`select customer_id from user_accounts where normalized_email='${customerEmail}'`),quoteId=crypto.randomUUID(),bookingId=crypto.randomUUID(),invoiceId=crypto.randomUUID(),accountId=sql(`select id from financial_accounts where customer_id='${customerId}' and currency='ZAR'`),reference=`VC-INVG1A${run.replaceAll('-','').toUpperCase()}`;
    const bookingReference=`VC-G1A-${run}`.toUpperCase(),invoiceNumber=`INV-G1A-${run}`.toUpperCase();
    sql(`insert into quotes(id,quote_number,customer_id,status,traveller_count,total_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${quoteId}','Q-G1A-${run}','${customerId}','ACCEPTED',1,12500,'ZAR',now(),now(),'acceptance','acceptance',0); insert into bookings(id,quote_id,customer_id,booking_reference,idempotency_key,status,quoted_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${bookingId}','${quoteId}','${customerId}','${bookingReference}','G1A-${run}','DEPOSIT_PENDING',12500,'ZAR',now(),now(),'acceptance','acceptance',0); insert into booking_payment_summary(id,booking_id,quoted_amount,deposit_due,deposit_paid,balance_due,balance_paid,currency,payment_status,created_at,updated_at,created_by,updated_by,version) values ('${crypto.randomUUID()}','${bookingId}',12500,12500,0,0,0,'ZAR','DEPOSIT_PENDING',now(),now(),'acceptance','acceptance',0); insert into financial_invoices(id,invoice_number,account_id,customer_id,booking_reference,currency,status,allocated_amount,credited_amount,version,created_at,updated_at,created_by,updated_by) values ('${invoiceId}','${invoiceNumber}','${accountId}','${customerId}','${bookingReference}','ZAR','ISSUED',0,0,0,now(),now(),'acceptance','acceptance'); insert into financial_invoice_lines(invoice_id,position,description,quantity,unit_price,tax_rate) values ('${invoiceId}',0,'DEV-005G1A customer journey',1,12500,0);`);
    await browserLogin(page,customerEmail);
    for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto(`${web}/bank-transfer/?api=local`,{waitUntil:'networkidle'});assert.equal(await page.getByText('DEV-005G1A Acceptance Bank').isVisible(),true);assert.equal(await page.getByText('ZAR',{exact:true}).isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}
    await page.goto(`${web}/bank-transfer/new/?api=local`,{waitUntil:'networkidle'});if(!await page.getByLabel('Invoice').count())throw new Error(`Review form unavailable: ${await page.locator('body').innerText()}`);await page.getByLabel('Invoice').selectOption('0');assert.equal(await page.getByText(reference,{exact:true}).isVisible(),true);await page.getByLabel('Bank account used for transfer').fill('Acceptance customer account');await page.getByRole('button',{name:'Create review case'}).click();await page.waitForURL(/bank-transfer\/details/);const reviewId=new URL(page.url()).searchParams.get('id');assert.match(reviewId,/^[0-9a-f-]{36}$/);
    const generator=await browser.newPage();await generator.setContent('<h1>DEV-005G1A transfer proof</h1>');await generator.pdf({path:'/tmp/virtcruise-dev005g1a-proof.pdf',format:'A4'});await generator.close();await page.getByLabel('Choose proof file').setInputFiles('/tmp/virtcruise-dev005g1a-proof.pdf');await page.getByRole('button',{name:'Upload proof'}).click();await page.locator('[data-upload-state]').getByText(/proof has been received/).waitFor();await page.waitForTimeout(900);await page.goto(`${web}/bank-transfer/details/?api=local&id=${reviewId}`,{waitUntil:'networkidle'});assert.equal(await page.getByText('Proof Accepted',{exact:true}).isVisible(),true);assert.equal(await page.getByText('Awaiting Finance Review',{exact:true}).isVisible(),true);
    const stored=JSON.stringify(await page.evaluate(()=>({local:{...localStorage},session:{...sessionStorage}})));assert.doesNotMatch(stored,/transfer-proof\.pdf|%PDF|accessToken|refreshToken|INV-G1A/);
    const other=(await apiLogin(otherEmail)).accessToken,consultant=(await apiLogin(consultantEmail)).accessToken,admin=(await apiLogin(adminEmail)).accessToken;
    assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}`,{token:other})).response.status,403);const proofId=sql(`select id from bank_transfer_proof_documents where review_case_id='${reviewId}'`);assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}/proofs/${proofId}`,{token:other})).response.status,403);assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}`)).response.status,401);assert.equal((await json('/api/v1/bank-transfer/integrations',{token:consultant})).response.status,403);assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}`,{token:admin})).response.status,200);
    await page.getByRole('button',{name:'Logout'}).click();const financeContext=await browser.newContext({viewport:{width:1280,height:900}}),financePage=await financeContext.newPage();await browserLogin(financePage,financeEmail);await financePage.goto(`${web}/finance/bank-transfers/details/?api=local&id=${reviewId}`,{waitUntil:'networkidle'});if(!await financePage.getByRole('button',{name:'Assign to me'}).count())throw new Error(`Finance case unavailable: ${await financePage.locator('body').innerText()}`);await financePage.getByRole('button',{name:'Assign to me'}).click();await financePage.getByRole('button',{name:'Remove assignment'}).waitFor();await financePage.getByRole('button',{name:'Start review'}).click();await financePage.getByRole('button',{name:'Approve'}).waitFor();await financePage.getByLabel(/Comment \(maximum/).fill('Acceptance-only internal comment');await financePage.getByRole('button',{name:'Add internal comment'}).click();await financePage.getByText('Internal Finance comment added.').waitFor();await financePage.getByRole('button',{name:'Securely view proof'}).click();const dialog=financePage.getByRole('dialog');await dialog.waitFor();assert.match(await dialog.locator('iframe').getAttribute('src'),/^blob:/);await financePage.getByRole('button',{name:'Close proof viewer'}).click();await financePage.getByRole('button',{name:'Approve'}).click();await financePage.getByLabel(/I attest/).check();await financePage.getByLabel('Approval reason').fill('Cleared funds independently verified');await financePage.getByRole('button',{name:'Confirm approval'}).click();await financePage.getByText('Approved',{exact:true}).waitFor();await financeContext.close();
    await eventually(async()=>assert.equal(sql(`select count(*) from financial_payments where payment_reference='${reference}'`),'1'));
    await page.close();const continuedContext=await browser.newContext(),continued=await continuedContext.newPage();await browserLogin(continued,customerEmail);await continued.goto(`${web}/bank-transfer/details/?api=local&id=${reviewId}`,{waitUntil:'networkidle'});assert.equal(await continued.getByText('Payment Recorded',{exact:true}).isVisible(),true);assert.match(await continued.locator('body').innerText(),/BTR-/);assert.match(await continued.locator('body').innerText(),/CONFIRMED/);await continuedContext.close();
    const otherReceipts=await json('/api/v1/financial/receipts?page=0&size=100',{token:other});assert.equal(otherReceipts.response.status,200);assert.equal(otherReceipts.data.content.some(item=>item.paymentReference===reference),false);
    assert.equal(sql(`select (select count(*) from bank_transfer_review_cases where id='${reviewId}'),(select count(*) from bank_transfer_proof_documents where review_case_id='${reviewId}' and status='ACCEPTED'),(select count(*) from financial_payments where payment_reference='${reference}'),(select count(*) from financial_receipts where payment_reference='${reference}'),(select count(*) from notification_intents where recipient_id='${customerId}' and source_event_type='ReceiptIssued')`),'1|1|1|1|1');
    const balance=sql(`select coalesce(sum(case when side='DEBIT' then amount else -amount end),0) from financial_ledger_lines where entry_id in (select id from financial_ledger_entries where source_id in (select id::text from financial_payments where payment_reference='${reference}'))`);assert.equal(Number(balance),0);
  }finally{await context.close();await browser.close();}
});
