import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright-core';
import { waitForApplicationReady } from './helpers/browser-acceptance.mjs';

const enabled = process.env.RUN_CUSTOMER_BANK_TRANSFER_REAL_ACCEPTANCE === 'true';
const web = process.env.BANK_TRANSFER_ACCEPTANCE_WEB || 'http://localhost:15003';
const api = process.env.BANK_TRANSFER_ACCEPTANCE_API || 'http://localhost:8080';
const localKey = process.env.LOCAL_AUTH_TEST_KEY || '';
const fakeSmtpApi = process.env.FAKE_SMTP_API || '';
const dbEnv = {...process.env,PGHOST:process.env.PGHOST||'127.0.0.1',PGPORT:process.env.PGPORT||'55441',PGDATABASE:process.env.PGDATABASE||'virtcruise_dev005g1b',PGUSER:process.env.PGUSER||'virtcruise_test',PGPASSWORD:process.env.PGPASSWORD||'dev005g1b_test_only'};
const password = 'Acceptance-Only-2026!';
const replacementFormat = process.env.REPLACEMENT_FORMAT === 'png' ? 'png' : 'jpeg';
const run = `g1b-${replacementFormat}-${Date.now()}`;
const email = name => `${run}-${name}@test.invalid`;
const sql = statement => execFileSync('psql',['-v','ON_ERROR_STOP=1','-At','-F','|','-c',statement],{env:dbEnv,encoding:'utf8'}).trim();
const eventually = async (action, timeout=15000) => { const until=Date.now()+timeout; let last; while(Date.now()<until){try{return await action();}catch(error){last=error;await new Promise(resolve=>setTimeout(resolve,250));}}throw last; };
async function json(path,{token,method='GET',body,key}={}){const response=await fetch(`${api}${path}`,{method,headers:{Accept:'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...(body?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined});return {response,data:(await response.json().catch(()=>null))?.data};}
async function browserRegisterAndVerify(page,address,name){await page.goto(`${web}/register/?api=local`);await waitForApplicationReady(page);await page.getByLabel('First name').fill(name);await page.getByLabel('Last name').fill('Acceptance');await page.getByLabel('Email').fill(address);await page.locator('#password').fill(password);await page.locator('#confirmPassword').fill(password);await page.getByLabel(/terms/i).check();await page.getByLabel(/privacy/i).check();await page.getByRole('button',{name:/create account/i}).click();await page.getByText(/check your email/i).waitFor();let token;if(fakeSmtpApi){token=await eventually(async()=>{const response=await fetch(`${fakeSmtpApi}/api/user/${encodeURIComponent(address)}/messages/INBOX`);assert.equal(response.status,200);const messages=await response.json(),mime=String(messages.at(-1)?.mimeMessage||'').replace(/=\r?\n/g,'').replaceAll('=3D','=').replaceAll('&amp;','&');const match=mime.match(/[?&]token=([^&\s<"]+)/);assert.ok(match);return decodeURIComponent(match[1]);});}else{const url=new URL('/api/v1/auth/development/token',api);url.searchParams.set('email',address);url.searchParams.set('purpose','VERIFICATION');const tokenResponse=await fetch(url,{headers:{'X-Local-Test-Key':localKey}});assert.equal(tokenResponse.status,200);token=(await tokenResponse.json()).data.token;}await page.goto(`${web}/verify-email/?api=local&token=${encodeURIComponent(token)}`);await waitForApplicationReady(page);await page.getByText(/verified|verification complete/i).waitFor();}
async function browserLogin(page,address){await page.goto(`${web}/signin/?api=local`);await waitForApplicationReady(page);await page.getByLabel('Email address').fill(address);await page.locator('#password').fill(password);await Promise.all([page.waitForURL(/\/(?:account|dashboard)\//),page.getByRole('button',{name:/sign in/i}).click()]);}
async function apiLogin(address){const result=await json('/api/v1/auth/login',{method:'POST',body:{email:address,password,deviceName:'DEV-005G1A'}});assert.equal(result.response.status,200);return result.data;}

test('complete real customer bank-transfer journey',{skip:!enabled,timeout:180000},async()=>{
  assert.ok(localKey.length>=24);
  assert.equal(sql("select current_setting('server_version'),current_setting('server_encoding'),current_setting('TimeZone'),current_setting('password_encryption')"),'18.4|UTF8|UTC|scram-sha-256');
  assert.equal(sql("select string_agg(version,',' order by installed_rank) from flyway_schema_history where success"),'1,2,3,4,5,6,7,8,9,10,11,12,13,14');
  sql("update bank_account_configuration set display_name='ZAR transfers',bank_name='DEV-005G1B Acceptance Bank',account_name='Virtcruise Travels',account_number='123456789',branch_code='123456',swift_code='TESTZAXX',customer_instructions='Allow two business days.',reference_prefix='VC',reference_rules='Use the exact reference shown.',reconciliation_identifier='DEV005G1B-ZAR',updated_at=now() where currency='ZAR' and active");assert.equal(sql("select currency from bank_account_configuration where currency='ZAR' and active"),'ZAR');
  const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
  const customerEmail=email('customer-a'),otherEmail=email('customer-b'),financeEmail=email('finance'),consultantEmail=email('consultant'),adminEmail=email('admin');
  const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'});const page=await context.newPage();
  try{
    await browserRegisterAndVerify(page,customerEmail,'Customer');
    for(const [address,name] of [[otherEmail,'Other'],[financeEmail,'Finance'],[consultantEmail,'Consultant'],[adminEmail,'Admin']]){const p=await browser.newPage();await browserRegisterAndVerify(p,address,name);await p.close();}
    sql(`${[['finance','ROLE_FINANCE'],['consultant','ROLE_CONSULTANT'],['admin','ROLE_ADMIN']].map(([name,role])=>`delete from user_roles where user_account_id=(select id from user_accounts where normalized_email='${email(name)}'); insert into user_roles(user_account_id,role_id) select u.id,r.id from user_accounts u cross join roles r where u.normalized_email='${email(name)}' and r.name='${role}'; update user_accounts set account_type='STAFF',customer_id=null where normalized_email='${email(name)}';`).join(' ')}`);
    const customerId=sql(`select customer_id from user_accounts where normalized_email='${customerEmail}'`),quoteId=crypto.randomUUID(),bookingId=crypto.randomUUID(),invoiceId=crypto.randomUUID(),accountId=sql(`select id from financial_accounts where customer_id='${customerId}' and currency='ZAR'`),reference=`VC-INVG1B${run.replaceAll('-','').toUpperCase()}`;
    const bookingReference=`VC-G1B-${run}`.toUpperCase(),invoiceNumber=`INV-G1B-${run}`.toUpperCase();
    sql(`insert into quotes(id,quote_number,customer_id,status,traveller_count,total_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${quoteId}','Q-G1B-${run}','${customerId}','ACCEPTED',1,12500,'ZAR',now(),now(),'acceptance','acceptance',0); insert into bookings(id,quote_id,customer_id,booking_reference,idempotency_key,status,quoted_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${bookingId}','${quoteId}','${customerId}','${bookingReference}','G1B-${run}','DEPOSIT_PENDING',12500,'ZAR',now(),now(),'acceptance','acceptance',0); insert into booking_payment_summary(id,booking_id,quoted_amount,deposit_due,deposit_paid,balance_due,balance_paid,currency,payment_status,created_at,updated_at,created_by,updated_by,version) values ('${crypto.randomUUID()}','${bookingId}',12500,12500,0,0,0,'ZAR','DEPOSIT_PENDING',now(),now(),'acceptance','acceptance',0); insert into financial_invoices(id,invoice_number,account_id,customer_id,booking_reference,currency,status,allocated_amount,credited_amount,version,created_at,updated_at,created_by,updated_by) values ('${invoiceId}','${invoiceNumber}','${accountId}','${customerId}','${bookingReference}','ZAR','ISSUED',0,0,0,now(),now(),'acceptance','acceptance'); insert into financial_invoice_lines(invoice_id,position,description,quantity,unit_price,tax_rate) values ('${invoiceId}',0,'DEV-005G1B customer journey',1,12500,0);`);
    await browserLogin(page,customerEmail);
    for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto(`${web}/bank-transfer/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);const bankPage=await page.locator('body').innerText();assert.match(bankPage,/DEV-005G1B Acceptance Bank/);assert.match(bankPage,/ZAR/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}
    await page.goto(`${web}/bank-transfer/new/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);if(!await page.getByLabel('Invoice').count())throw new Error(`Review form unavailable: ${await page.locator('body').innerText()}`);await page.getByLabel('Invoice').selectOption('0');await page.getByText(reference,{exact:true}).waitFor();await page.getByLabel('Bank account used for transfer').fill('Acceptance customer account');await page.getByRole('button',{name:'Create review case'}).click();await page.waitForURL(/bank-transfer\/details/);const reviewId=new URL(page.url()).searchParams.get('id');assert.match(reviewId,/^[0-9a-f-]{36}$/);
    const initialPath=`/tmp/virtcruise-${run}-initial.pdf`,replacementPath=`/tmp/virtcruise-${run}-replacement.${replacementFormat==='jpeg'?'jpg':'png'}`;const generator=await browser.newPage();await generator.setContent('<h1>DEV-005G1B initial transfer proof</h1>');await generator.pdf({path:initialPath,format:'A4'});await generator.setContent(`<h1>DEV-005G1B ${replacementFormat} replacement proof</h1>`);await generator.screenshot({path:replacementPath,type:replacementFormat,quality:replacementFormat==='jpeg'?90:undefined});await generator.close();await page.getByLabel('Choose proof file').setInputFiles(initialPath);await page.getByRole('button',{name:'Upload proof'}).click();await page.locator('[data-upload-state]').getByText(/proof has been received/).waitFor();await page.waitForTimeout(900);await page.goto(`${web}/bank-transfer/details/?api=local&id=${reviewId}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);assert.equal(await page.getByText('Proof Accepted',{exact:true}).isVisible(),true);assert.equal(await page.getByText('Awaiting Finance Review',{exact:true}).isVisible(),true);
    const stored=JSON.stringify(await page.evaluate(()=>({local:{...localStorage},session:{...sessionStorage}})));assert.doesNotMatch(stored,/initial\.pdf|replacement\.(?:jpg|png)|%PDF|accessToken|refreshToken|INV-G1B/);
    const other=(await apiLogin(otherEmail)).accessToken,consultant=(await apiLogin(consultantEmail)).accessToken,admin=(await apiLogin(adminEmail)).accessToken;
    assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}`,{token:other})).response.status,403);const proofId=sql(`select id from bank_transfer_proof_documents where review_case_id='${reviewId}'`);assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}/proofs/${proofId}`,{token:other})).response.status,403);assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}`)).response.status,401);assert.equal((await json('/api/v1/bank-transfer/integrations',{token:consultant})).response.status,403);assert.equal((await json(`/api/v1/bank-transfer/reviews/${reviewId}`,{token:admin})).response.status,200);
    await page.getByRole('button',{name:'Logout'}).click();const financeContext=await browser.newContext({viewport:{width:1280,height:900}}),financePage=await financeContext.newPage();await browserLogin(financePage,financeEmail);await financePage.goto(`${web}/finance/bank-transfers/details/?api=local&id=${reviewId}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(financePage);if(!await financePage.getByRole('button',{name:'Assign to me'}).count())throw new Error(`Finance case unavailable: ${await financePage.locator('body').innerText()}`);await financePage.getByRole('button',{name:'Assign to me'}).click();await financePage.getByRole('button',{name:'Remove assignment'}).waitFor();await financePage.getByRole('button',{name:'Start review'}).click();await financePage.getByRole('button',{name:'Reject'}).waitFor();await financePage.getByLabel(/Comment \(maximum/).fill('Private Finance comment: image evidence requires replacement');await financePage.getByRole('button',{name:'Add internal comment'}).click();await financePage.getByText('Internal Finance comment added.').waitFor();await financePage.getByRole('button',{name:'Reject'}).click();await financePage.getByLabel('Permit a replacement proof').check();await financePage.getByLabel(/Customer-safe reason/).fill('Please upload a clearer bank-issued image.');await financePage.getByLabel(/Internal rejection reason/).fill('Private Finance mismatch details');await financePage.getByRole('button',{name:'Confirm rejection'}).click();await financePage.getByText('Rejected',{exact:true}).waitFor();
    assert.equal(sql(`select (select count(*) from financial_payments where payment_reference='${reference}'),(select count(*) from financial_receipts where payment_reference='${reference}'),(select count(*) from financial_ledger_entries where source_id in (select id::text from financial_payments where payment_reference='${reference}'))`),'0|0|0');
    const replacementContext=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'}),replacementPage=await replacementContext.newPage();await browserLogin(replacementPage,customerEmail);for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){await replacementPage.setViewportSize(viewport);await replacementPage.goto(`${web}/bank-transfer/details/?api=local&id=${reviewId}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(replacementPage);const body=await replacementPage.locator('body').innerText();assert.match(body,/Please upload a clearer bank-issued image\./);assert.doesNotMatch(body,/Private Finance mismatch|Private Finance comment/);assert.equal(await replacementPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}await replacementPage.getByRole('button',{name:'Begin replacement upload'}).focus();assert.equal(await replacementPage.getByRole('button',{name:'Begin replacement upload'}).evaluate(element=>element===document.activeElement),true);await replacementPage.getByRole('button',{name:'Begin replacement upload'}).press('Enter');await replacementPage.getByLabel('Upload replacement proof').waitFor();await replacementPage.getByLabel('Upload replacement proof').setInputFiles(replacementPath);await replacementPage.getByRole('button',{name:'Upload proof'}).click();await replacementPage.locator('[data-upload-state]').getByText(/proof has been received/).waitFor();await replacementPage.waitForTimeout(900);await replacementContext.close();
    await financePage.goto(`${web}/finance/bank-transfers/details/?api=local&id=${reviewId}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(financePage);await financePage.getByRole('button',{name:'Assign to me'}).click();await financePage.getByRole('button',{name:'Remove assignment'}).waitFor();await financePage.getByRole('button',{name:'Start review'}).click();await financePage.getByRole('button',{name:'Approve'}).waitFor();await financePage.getByRole('button',{name:'Securely view proof'}).click();const dialog=financePage.getByRole('dialog');await dialog.waitFor();assert.match(await dialog.locator('.proof-media iframe, .proof-media img').getAttribute('src'),/^blob:/);await financePage.getByRole('button',{name:'Close proof viewer'}).click();await financePage.getByRole('button',{name:'Approve'}).click();await financePage.getByLabel(/I attest/).check();await financePage.getByLabel('Approval reason').fill('Replacement proof and cleared funds independently verified');await financePage.getByRole('button',{name:'Confirm approval'}).click();await financePage.getByText('Approved',{exact:true}).waitFor();await financeContext.close();
    await eventually(async()=>assert.equal(sql(`select count(*) from financial_payments where payment_reference='${reference}'`),'1'));
    await page.close();const continuedContext=await browser.newContext(),continued=await continuedContext.newPage();await browserLogin(continued,customerEmail);await continued.goto(`${web}/bank-transfer/details/?api=local&id=${reviewId}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(continued);assert.equal(await continued.getByText('Payment Recorded',{exact:true}).isVisible(),true);assert.match(await continued.locator('body').innerText(),/BTR-/);assert.match(await continued.locator('body').innerText(),/CONFIRMED/);await continuedContext.close();
    const otherReceipts=await json('/api/v1/financial/receipts?page=0&size=100',{token:other});assert.equal(otherReceipts.response.status,200);assert.equal(otherReceipts.data.content.some(item=>item.paymentReference===reference),false);
    assert.equal(sql(`select (select count(*) from bank_transfer_review_cases where id='${reviewId}'),(select count(*) from bank_transfer_review_cycles where review_case_id='${reviewId}'),(select count(*) from bank_transfer_review_cycles where review_case_id='${reviewId}' and cycle_number=1 and decision='REJECTED'),(select count(*) from bank_transfer_review_cycles where review_case_id='${reviewId}' and cycle_number=2 and decision='APPROVED'),(select count(*) from bank_transfer_proof_documents where review_case_id='${reviewId}'),(select count(*) from bank_transfer_proof_documents where review_case_id='${reviewId}' and status='SUPERSEDED'),(select count(*) from bank_transfer_proof_documents where review_case_id='${reviewId}' and status='ACCEPTED'),(select count(*) from financial_payments where payment_reference='${reference}'),(select count(*) from financial_receipts where payment_reference='${reference}'),(select count(*) from notification_intents where recipient_id='${customerId}' and source_event_type='ReceiptIssued')`),'1|2|1|1|2|1|1|1|1|1');
    const balance=sql(`select coalesce(sum(case when side='DEBIT' then amount else -amount end),0) from financial_ledger_lines where entry_id in (select id from financial_ledger_entries where source_id in (select id::text from financial_payments where payment_reference='${reference}'))`);assert.equal(Number(balance),0);
  }finally{await context.close();await browser.close();}
});
