import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright-core';
import { enforceOfflineAcceptance, waitForApplicationReady } from './helpers/browser-acceptance.mjs';

const enabled = process.env.RUN_PARTIAL_FULL_REAL_ACCEPTANCE === 'true';
const web = process.env.PARTIAL_FULL_WEB || 'http://localhost:15003';
const api = process.env.PARTIAL_FULL_API || 'http://localhost:8080';
const smtpApi = process.env.FAKE_SMTP_API || 'http://127.0.0.1:18025';
const localKey = process.env.LOCAL_AUTH_TEST_KEY || '';
const dbEnv = {...process.env,PGHOST:process.env.PGHOST||'127.0.0.1',PGPORT:process.env.PGPORT||'55443',PGDATABASE:process.env.PGDATABASE||'vc_g3',PGUSER:process.env.PGUSER||'vc_g3',PGPASSWORD:process.env.PGPASSWORD||'vc_g3_disposable'};
const password='Acceptance-Only-2026!', run=`g3-${Date.now()}`, customerEmail=`${run}-customer@test.invalid`, financeEmail=`${run}-finance@test.invalid`;
const sql=statement=>execFileSync('psql',['-v','ON_ERROR_STOP=1','-At','-F','|','-c',statement],{env:dbEnv,encoding:'utf8'}).trim();
const eventually=async(action,timeout=30000)=>{const end=Date.now()+timeout;let last;while(Date.now()<end){try{return await action();}catch(error){last=error;await new Promise(resolve=>setTimeout(resolve,250));}}throw last;};
async function request(path,{token,method='GET',body,key}={}){const response=await fetch(`${api}${path}`,{method,headers:{Accept:'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...(body?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined});const value=await response.json().catch(()=>null);return {response,data:value?.data,value};}
async function register(page,email,name){await page.goto(`${web}/register/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await page.getByLabel('First name').fill(name);await page.getByLabel('Last name').fill('Acceptance');await page.getByLabel('Email').fill(email);await page.locator('#password').fill(password);await page.locator('#confirmPassword').fill(password);await page.getByLabel(/terms/i).check();await page.getByLabel(/privacy/i).check();await page.getByRole('button',{name:/create account/i}).click();await page.getByText(/check your email/i).waitFor();const token=await eventually(async()=>{const verification=(await messages()).find(item=>item.recipient===email&&/Subject: Verify your Virtcruise account/i.test(item.raw));assert.ok(verification);const match=verification.raw.match(/verify-email\/\?token=([^\s<"]+)/);assert.ok(match);return match[1];});await page.goto(`${web}/verify-email/?api=local&token=${encodeURIComponent(token)}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);}
async function login(page,email){await page.goto(`${web}/signin/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await page.getByLabel('Email address').fill(email);await page.locator('#password').fill(password);await Promise.all([page.waitForURL(/\/(?:account|dashboard)\//),page.getByRole('button',{name:/sign in/i}).click()]);}
async function apiLogin(email){const result=await request('/api/v1/auth/login',{method:'POST',body:{email,password,deviceName:'DEV-005G3'}});assert.equal(result.response.status,200,JSON.stringify(result.value));return result.data;}
async function approve(page,id){await page.goto(`${web}/finance/bank-transfers/details/?api=local&id=${id}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await eventually(async()=>{if(!await page.getByRole('button',{name:'Assign to me'}).count()){await page.getByRole('button',{name:'Refresh case'}).click();await page.waitForTimeout(250);}assert.equal(await page.getByRole('button',{name:'Assign to me'}).count(),1);});await page.getByRole('button',{name:'Assign to me'}).click();await page.getByRole('button',{name:'Remove assignment'}).waitFor();await page.getByRole('button',{name:'Start review'}).click();await page.getByRole('button',{name:'Securely view proof'}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();assert.match(await dialog.locator('iframe').getAttribute('src'),/^blob:/);await page.getByRole('button',{name:'Close proof viewer'}).click();await page.getByRole('button',{name:'Approve'}).click();await page.getByLabel(/I attest/).check();await page.getByLabel('Approval reason').fill('Cleared funds independently verified for DEV-005G3');await page.getByRole('button',{name:'Confirm approval'}).click();await page.getByText('Approved',{exact:true}).waitFor();}
async function createAndUpload(page,amount,proofName){await page.goto(`${web}/bank-transfer/new/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await page.getByLabel('Invoice').selectOption('0');await page.waitForFunction(()=>!document.querySelector('#reviewForm [type="submit"]')?.disabled);assert.ok(Number(await page.getByLabel('Transfer amount').inputValue())>=Number(amount));await page.getByLabel('Transfer amount').fill(amount);await page.getByLabel('Bank account used for transfer').fill('DEV-005G3 controlled customer account');await page.getByRole('button',{name:'Create review case'}).click();await page.waitForURL(/bank-transfer\/details/);const id=new URL(page.url()).searchParams.get('id');const generator=await page.context().browser().newPage();await generator.setContent(`<h1>${proofName}</h1>`);const path=`/tmp/${proofName}.pdf`;await generator.pdf({path,format:'A4'});await generator.close();await page.getByLabel('Choose proof file').setInputFiles(path);await page.getByRole('button',{name:'Upload proof'}).click();await page.locator('[data-upload-state]').getByText(/proof has been received/).waitFor();return {id,path};}
async function messages(){const response=await fetch(`${smtpApi}/messages`);assert.equal(response.status,200);return response.json();}

test('one real invoice progresses from partial to full payment with deterministic email evidence',{skip:!enabled,timeout:240000},async()=>{
 assert.ok(localKey.length>=24);assert.equal(sql("select current_setting('server_version'),current_setting('server_encoding'),current_setting('TimeZone'),current_setting('password_encryption')"),'18.4|UTF8|UTC|scram-sha-256');assert.equal(sql("select string_agg(version,',' order by installed_rank) from flyway_schema_history where success"),'1,2,3,4,5,6,7,8,9,10,11,12,13,14');sql("update bank_account_configuration set display_name='ZAR transfers',bank_name='DEV-005G3 Acceptance Bank',account_name='Virtcruise Travels',account_number='123456789',branch_code='123456',swift_code='TESTZAXX',customer_instructions='Allow two business days.',reference_prefix='VC',reference_rules='Use the exact reference shown.',reconciliation_identifier='DEV005G3-ZAR',updated_at=now() where currency='ZAR' and active");assert.equal(sql("select currency from bank_account_configuration where currency='ZAR' and active"),'ZAR');
 const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'});await enforceOfflineAcceptance(context,{allowedOrigins:[new URL(web).origin,new URL(api).origin]});const page=await context.newPage(),consoleErrors=[],failed=[];page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('requestfailed',request=>failed.push(new URL(request.url()).origin+new URL(request.url()).pathname));
 let firstPath,secondPath;
 try{
  await register(page,customerEmail,'Partial');const staff=await context.newPage();await register(staff,financeEmail,'Finance');await staff.close();sql(`delete from user_roles where user_account_id=(select id from user_accounts where normalized_email='${financeEmail}');insert into user_roles(user_account_id,role_id) select u.id,r.id from user_accounts u cross join roles r where u.normalized_email='${financeEmail}' and r.name='ROLE_FINANCE';update user_accounts set account_type='STAFF',customer_id=null where normalized_email='${financeEmail}';`);
  const customerId=sql(`select customer_id from user_accounts where normalized_email='${customerEmail}'`),accountId=sql(`select id from financial_accounts where customer_id='${customerId}' and currency='ZAR'`),quoteId=crypto.randomUUID(),bookingId=crypto.randomUUID(),invoiceId=crypto.randomUUID(),bookingReference=`VC-G3-${run}`.toUpperCase(),invoiceNumber=`INV-G3-${run}`.toUpperCase();
  sql(`insert into quotes(id,quote_number,customer_id,status,traveller_count,total_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${quoteId}','Q-${run}','${customerId}','ACCEPTED',1,10000,'ZAR',now(),now(),'acceptance','acceptance',0);insert into bookings(id,quote_id,customer_id,booking_reference,idempotency_key,status,quoted_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${bookingId}','${quoteId}','${customerId}','${bookingReference}','${run}','DEPOSIT_PENDING',10000,'ZAR',now(),now(),'acceptance','acceptance',0);insert into booking_payment_summary(id,booking_id,quoted_amount,deposit_due,deposit_paid,balance_due,balance_paid,currency,payment_status,created_at,updated_at,created_by,updated_by,version) values ('${crypto.randomUUID()}','${bookingId}',10000,10000,0,0,0,'ZAR','DEPOSIT_PENDING',now(),now(),'acceptance','acceptance',0);insert into financial_invoices(id,invoice_number,account_id,customer_id,booking_reference,currency,status,allocated_amount,credited_amount,version,created_at,updated_at,created_by,updated_by) values ('${invoiceId}','${invoiceNumber}','${accountId}','${customerId}','${bookingReference}','ZAR','ISSUED',0,0,0,now(),now(),'acceptance','acceptance');insert into financial_invoice_lines(invoice_id,position,description,quantity,unit_price,tax_rate) values ('${invoiceId}',0,'DEV-005G3 partial-to-full acceptance',1,10000,0);`);
  await login(page,customerEmail);for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto(`${web}/bank-transfer/new/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await page.getByLabel('Invoice').selectOption('0');assert.match(await page.getByLabel('Invoice').locator('option:checked').textContent(),/ZAR.*10[,. ]?000/);assert.equal(Number(await page.getByLabel('Transfer amount').inputValue()),10000);const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth}));assert.ok(dimensions.scrollWidth<=dimensions.innerWidth+1,`overflow at ${viewport.width}: ${JSON.stringify(dimensions)}`);}const first=await createAndUpload(page,'4000.00',`${run}-first-proof`);firstPath=first.path;assert.equal(sql(`select count(*) from financial_payments where customer_id='${customerId}'`),'0');
  const financeContext=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});await enforceOfflineAcceptance(financeContext,{allowedOrigins:[new URL(web).origin,new URL(api).origin]});const financePage=await financeContext.newPage();await login(financePage,financeEmail);await approve(financePage,first.id);await financeContext.close();
  await eventually(async()=>assert.equal(sql(`select count(*) from financial_payments where customer_id='${customerId}'`),'1'));await eventually(async()=>assert.equal(sql(`select count(*) from notification_intents where recipient_id='${customerId}' and notification_type in ('PAYMENT_RECORDED','RECEIPT_ISSUED') and status='SENT'`),'2'));
  assert.equal(sql(`select amount from financial_payments where customer_id='${customerId}'`),'4000.0000');assert.equal(sql(`select amount from financial_payment_allocations where payment_id in(select id from financial_payments where customer_id='${customerId}')`),'4000.0000');assert.equal(sql(`select status||'|'||allocated_amount||'|'||(10000-allocated_amount) from financial_invoices where id='${invoiceId}'`),'PARTIALLY_PAID|4000.0000|6000.0000');assert.equal(sql(`select status from bookings where id='${bookingId}'`),'DEPOSIT_PENDING');assert.equal(sql(`select count(*) from notification_intents where recipient_id='${customerId}' and notification_type='BOOKING_CONFIRMED'`),'0');
  let mail=await eventually(async()=>{const value=await messages();assert.ok(value.filter(item=>item.recipient===customerEmail).length>=4);return value.filter(item=>item.recipient===customerEmail);});const partialRecorded=mail.find(item=>/Subject: Your bank transfer was recorded/i.test(item.raw));const partialReceipt=mail.find(item=>/Subject: Your Virtcruise receipt is available/i.test(item.raw));assert.ok(partialRecorded&&partialReceipt);assert.match(partialRecorded.raw,/4000 ZAR/);assert.match(partialRecorded.raw,/Remaining balance: 6000 ZAR/);assert.doesNotMatch(partialRecorded.raw,/booking is confirmed/i);for(const item of [partialRecorded,partialReceipt]){assert.match(item.raw,/Content-Type: text\/plain/i);assert.match(item.raw,/Content-Type: text\/html/i);assert.doesNotMatch(item.raw,/DEV-005G3 controlled customer account|storage|proof.*\.pdf|Authorization:|Bearer /i);}
  for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto(`${web}/financial/invoices/details/?api=local&id=${invoiceId}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);assert.equal(await page.getByText('ZAR 6,000.00').last().isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}assert.ok(failed.every(path=>['http://localhost:8080/api/v1/auth/session','http://localhost:8080/api/v1/bank-transfer/reviews/instructions'].includes(path)),JSON.stringify(failed));failed.length=0;
  const second=await createAndUpload(page,'6000.00',`${run}-second-proof`);secondPath=second.path;assert.notEqual(second.id,first.id);const financeContext2=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});await enforceOfflineAcceptance(financeContext2,{allowedOrigins:[new URL(web).origin,new URL(api).origin]});const financePage2=await financeContext2.newPage();await login(financePage2,financeEmail);await approve(financePage2,second.id);await financeContext2.close();
  await eventually(async()=>assert.equal(sql(`select count(*) from financial_payments where customer_id='${customerId}'`),'2'));await eventually(async()=>assert.equal(sql(`select count(*) from notification_intents where recipient_id='${customerId}' and notification_type in ('PAYMENT_RECORDED','RECEIPT_ISSUED','BOOKING_CONFIRMED') and status='SENT'`),'5'));
  assert.equal(sql(`select string_agg(amount::text,',' order by amount) from financial_payments where customer_id='${customerId}'`),'4000.0000,6000.0000');assert.equal(sql(`select sum(amount) from financial_payment_allocations where payment_id in(select id from financial_payments where customer_id='${customerId}')`),'10000.0000');assert.equal(sql(`select status||'|'||allocated_amount from financial_invoices where id='${invoiceId}'`),'PAID|10000.0000');assert.equal(sql(`select count(*) from financial_receipts where customer_id='${customerId}'`),'2');assert.equal(sql(`select count(*)||'|'||count(*) filter(where balance<>0) from(select e.id,sum(case when l.side='DEBIT' then l.amount else -l.amount end) balance from financial_ledger_entries e join financial_ledger_lines l on l.entry_id=e.id where e.source_id in(select payment_reference from financial_payments where customer_id='${customerId}') group by e.id)s`),'2|0');assert.equal(sql(`select status from bookings where id='${bookingId}'`),'CONFIRMED');assert.equal(sql(`select count(*) from booking_status_history where booking_id='${bookingId}' and new_status='CONFIRMED'`),'1');
  mail=await eventually(async()=>{const value=(await messages()).filter(item=>item.recipient===customerEmail);assert.equal(value.filter(item=>/Subject: Your bank transfer was recorded/i.test(item.raw)).length,2);assert.equal(value.filter(item=>/Subject: Your Virtcruise receipt is available/i.test(item.raw)).length,2);assert.equal(value.filter(item=>/Subject: Your booking is confirmed/i.test(item.raw)).length,1);return value;});const finalRecorded=mail.filter(item=>/Subject: Your bank transfer was recorded/i.test(item.raw)).find(item=>/Cleared funds of 6000 ZAR/.test(item.raw));assert.ok(finalRecorded);assert.match(finalRecorded.raw,/Remaining balance: 0 ZAR/);assert.match(mail.find(item=>/Subject: Your booking is confirmed/i.test(item.raw)).raw,new RegExp(bookingReference));
  sql(`update bank_transfer_outbox set status='PENDING',next_attempt_at=now(),published_at=null where aggregate_id in ('${first.id}','${second.id}') and event_type='ReviewApproved';update financial_outbox set status='PENDING',next_attempt_at=now(),published_at=null where correlation_id in(select correlation_id from bank_transfer_integration_executions where review_case_id in('${first.id}','${second.id}')) and event_type='ReceiptIssued';update bank_transfer_integration_outbox set status='PENDING',next_attempt_at=now(),published_at=null where execution_id in(select id from bank_transfer_integration_executions where review_case_id in('${first.id}','${second.id}'));`);await new Promise(resolve=>setTimeout(resolve,3000));assert.equal(sql(`select count(*) from financial_payments where customer_id='${customerId}'`),'2');assert.equal(sql(`select count(*) from financial_receipts where customer_id='${customerId}'`),'2');assert.equal(sql(`select count(*) from booking_status_history where booking_id='${bookingId}' and new_status='CONFIRMED'`),'1');assert.equal(sql(`select count(*) from notification_intents where recipient_id='${customerId}' and notification_type in ('PAYMENT_RECORDED','RECEIPT_ISSUED','BOOKING_CONFIRMED')`),'5');
  await page.goto(`${web}/financial/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);assert.match(await page.getByText('Open invoices').locator('..').innerText(),/Open invoices\s+0/);assert.equal(await page.getByText('None due').isVisible(),true);await page.goto(`${web}/financial/payments/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);for(const reference of sql(`select string_agg(payment_reference,'|' order by amount) from financial_payments where customer_id='${customerId}'`).split('|'))assert.equal(await page.getByText(reference,{exact:true}).isVisible(),true);await page.goto(`${web}/financial/receipts/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);for(const number of sql(`select string_agg(receipt_number,'|' order by created_at) from financial_receipts where customer_id='${customerId}'`).split('|'))assert.equal(await page.getByText(number,{exact:true}).isVisible(),true);assert.ok(failed.every(path=>path==='http://localhost:8080/api/v1/auth/session'));failed.length=0;await Promise.all([page.waitForURL(/signin|index\.html/),page.getByRole('button',{name:'Logout'}).click()]);await page.goto(`${web}/financial/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);assert.match(page.url(),/signin/);await page.goBack({waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await page.waitForTimeout(1000);assert.doesNotMatch(page.url(),/\/financial\//);assert.equal(await page.getByText(/Payment reference|Receipt history/).count(),0);const stored=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));assert.doesNotMatch(stored,/accessToken|refreshToken|first-proof|second-proof|financial_payments|storage_key/i);
  assert.equal(sql(`select (select count(*) from bank_transfer_review_cases where id in('${first.id}','${second.id}')),(select count(*) from bank_transfer_review_cycles where review_case_id in('${first.id}','${second.id}')),(select count(*) from bank_transfer_proof_documents where review_case_id in('${first.id}','${second.id}') and status='ACCEPTED'),(select count(*) from bank_transfer_integration_executions where review_case_id in('${first.id}','${second.id}') and status='COMPLETED'),(select count(*) from notification_attempts where intent_id in(select id from notification_intents where recipient_id='${customerId}'))`),'2|2|2|2|7');assert.equal(sql("select (select count(*) from bank_transfer_idempotency where status='PROCESSING'),(select count(*) from bank_transfer_outbox where status='PROCESSING'),(select count(*) from notification_intents where status='SENDING')"),'0|0|0');assert.deepEqual(consoleErrors,[]);assert.ok(failed.every(path=>['http://localhost:8080/api/v1/auth/session','http://localhost:8080/api/v1/packages','http://localhost:8080/api/v1/packages/featured','http://localhost:15003/images/favicon.png'].includes(path)));
 }finally{await context.close();await browser.close();}
});
