import test,{after,before} from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {launchChromium} from './helpers/playwright-runtime.mjs';
import {waitForApplicationReady} from './helpers/browser-acceptance.mjs';

const enabled=process.env.RUN_FINANCE_REAL_ACCEPTANCE==='true';
const api=process.env.FINANCE_ACCEPTANCE_API||'http://localhost:8080';
const web=process.env.FINANCE_ACCEPTANCE_WEB||'http://127.0.0.1:15002';
const dbEnv={...process.env,PGHOST:'127.0.0.1',PGPORT:'55435',PGDATABASE:'vc_d1',PGUSER:'vc_d1',PGPASSWORD:'vc_d1_disposable'};
const password='Acceptance-Only-2026!';
const runId=`d1-${process.pid}`;
const emails={customerA:`${runId}-customer-a@test.invalid`,customerB:`${runId}-customer-b@test.invalid`,finance1:`${runId}-finance-1@test.invalid`,finance2:`${runId}-finance-2@test.invalid`,consultant:`${runId}-consultant@test.invalid`,admin:`${runId}-admin@test.invalid`};
let browser,actors={},cases={},proofs={};

function sql(statement){return execFileSync('psql',['-v','ON_ERROR_STOP=1','-At','-F','|','-c',statement],{env:dbEnv,encoding:'utf8'}).trim();}
async function request(path,{token,method='GET',body,key,headers={}}={}){const response=await fetch(`${api}${path}`,{method,body:body===undefined?undefined:JSON.stringify(body),headers:{Accept:'application/json',...(body===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`} :{}),...(key?{'Idempotency-Key':key}:{}),...headers}});const value=await response.json().catch(()=>null);return {response,value,data:value?.data};}
async function register(email,name){const result=await request('/api/v1/auth/register',{method:'POST',body:{email,password,givenName:name,familyName:'Acceptance',termsAccepted:true,privacyAccepted:true,customerProfile:{phoneNumber:null,preferredContactMethod:'EMAIL'}}});assert.equal(result.response.status,202,JSON.stringify(result.value));}
async function login(email){const result=await request('/api/v1/auth/login',{method:'POST',body:{email,password,deviceName:'DEV-005D1 acceptance'}});assert.equal(result.response.status,200,JSON.stringify(result.value));return {token:result.data.accessToken,user:result.data.user};}
async function createCase(actor,suffix,hours=48){const booking=crypto.randomUUID(),invoice=crypto.randomUUID();sql(`set session_replication_role=replica; insert into bookings(id,quote_id,customer_id,booking_reference,idempotency_key,status,quoted_amount,currency,created_at,updated_at,created_by,updated_by,version) values ('${booking}','${crypto.randomUUID()}','${actor.user.customerId}','D1-${suffix}','D1B-${suffix}','PENDING',12500,'ZAR',now(),now(),'acceptance','acceptance',0); insert into financial_invoices(id,invoice_number,account_id,customer_id,currency,status,allocated_amount,credited_amount,version,created_at,updated_at,created_by,updated_by) values ('${invoice}','D1I-${suffix}','${crypto.randomUUID()}','${actor.user.customerId}','ZAR','ISSUED',0,0,0,now(),now(),'acceptance','acceptance'); reset session_replication_role;`);const result=await request('/api/v1/bank-transfer/reviews',{token:actor.token,method:'POST',key:`create-${suffix}`,body:{bookingId:booking,invoiceId:invoice,currency:'ZAR',amount:12500,bankAccount:'VC-ZAR-ACCEPTANCE',transferReference:`D1-${suffix}`,slaHours:hours}});assert.equal(result.response.status,200,JSON.stringify(result.value));return result.data;}
async function upload(actor,review,filePath,fileName,type,key){const form=new FormData();form.append('file',new Blob([readFileSync(filePath)],{type}),fileName);const response=await fetch(`${api}/api/v1/bank-transfer/reviews/${review.id}/proofs`,{method:'POST',headers:{Authorization:`Bearer ${actor.token}`,'Idempotency-Key':key},body:form});const value=await response.json();assert.equal(response.status,200,JSON.stringify(value));return value.data;}
async function mutate(actor,id,operation,body,key,method='POST'){return request(`/api/v1/bank-transfer/reviews/${id}/${operation}`,{token:actor.token,method,body,key});}
async function browserLogin(page,email){await page.goto(`${web}/signin/?api=local`);await waitForApplicationReady(page);await page.getByLabel('Email address').fill(email);await page.locator('input#password').fill(password);await Promise.all([page.waitForURL(/\/account\//),page.getByRole('button',{name:/sign in/i}).click()]);await page.getByRole('button',{name:'Logout'}).waitFor();}

before(async()=>{if(!enabled)return;browser=await launchChromium({headless:true,args:['--no-sandbox']});sql("truncate bank_transfer_proof_scan_attempts,bank_transfer_proof_audit,bank_transfer_proof_documents,bank_transfer_idempotency,bank_transfer_outbox,bank_transfer_audit,sla_tracking,finance_assignments,finance_review_comments,bank_transfer_review_cases cascade; set session_replication_role=replica; delete from financial_invoices where invoice_number like 'D1I-%'; delete from bookings where booking_reference like 'D1-%'; reset session_replication_role; delete from user_roles where user_account_id in (select id from user_accounts where normalized_email like 'd1-%@test.invalid'); delete from user_accounts where normalized_email like 'd1-%@test.invalid'; delete from customers where normalized_email like 'd1-%@test.invalid';");for(const [key,email] of Object.entries(emails))await register(email,key);const customerA=crypto.randomUUID(),customerB=crypto.randomUUID();sql(`insert into customers(id,first_name,last_name,email,normalized_email,created_at,updated_at,created_by,updated_by,version) values ('${customerA}','Customer','A','${emails.customerA}','${emails.customerA}',now(),now(),'acceptance','acceptance',0),('${customerB}','Customer','B','${emails.customerB}','${emails.customerB}',now(),now(),'acceptance','acceptance',0); update user_accounts set email_verified=true where normalized_email like 'd1-%@test.invalid'; update user_accounts set customer_id='${customerA}' where normalized_email='${emails.customerA}'; update user_accounts set customer_id='${customerB}' where normalized_email='${emails.customerB}'; ${[['finance1','ROLE_FINANCE'],['finance2','ROLE_FINANCE'],['consultant','ROLE_CONSULTANT'],['admin','ROLE_ADMIN']].map(([name,role])=>`delete from user_roles where user_account_id=(select id from user_accounts where normalized_email='${emails[name]}'); insert into user_roles(user_account_id,role_id) select u.id,r.id from user_accounts u cross join roles r where u.normalized_email='${emails[name]}' and r.name='${role}'; update user_accounts set account_type='STAFF',customer_id=null where normalized_email='${emails[name]}';`).join(' ')}`);for(const [key,email] of Object.entries(emails))actors[key]=await login(email);assert.deepEqual(actors.finance1.user.roles,['ROLE_FINANCE']);assert.deepEqual(actors.consultant.user.roles,['ROLE_CONSULTANT']);assert.deepEqual(actors.admin.user.roles,['ROLE_ADMIN']);
  const generator=await browser.newPage({viewport:{width:800,height:600}});await generator.setContent('<h1>Virtcruise proof acceptance</h1><p>Evidence only</p>');await generator.pdf({path:'/tmp/virtcruise-dev005d1/proof.pdf',format:'A4'});await generator.close();
  cases.pdf=await createCase(actors.customerA,'PDF');cases.jpeg=await createCase(actors.customerA,'JPEG');cases.png=await createCase(actors.customerA,'PNG');cases.approve=await createCase(actors.customerA,'APPROVE');cases.reject=await createCase(actors.customerA,'REJECT');cases.concurrent=await createCase(actors.customerA,'CONCURRENT');cases.customerB=await createCase(actors.customerB,'CUSTOMER-B');cases.unassigned=await createCase(actors.customerA,'UNASSIGNED');
  proofs.pdf=await upload(actors.customerA,cases.pdf,'/tmp/virtcruise-dev005d1/proof.pdf','accepted.pdf','application/pdf','proof-pdf');proofs.jpeg=await upload(actors.customerA,cases.jpeg,'images/about-virtcruise-office.jpg','accepted.jpg','image/jpeg','proof-jpeg');proofs.png=await upload(actors.customerA,cases.png,'images/favicon.png','accepted.png','image/png','proof-png');for(const name of ['approve','reject','concurrent','customerB'])proofs[name]=await upload(name==='customerB'?actors.customerB:actors.customerA,cases[name],'images/favicon.png',`${name}.png`,'image/png',`proof-${name}`);
});
after(async()=>{await browser?.close();});

test('real PostgreSQL Finance queue, browser authorization, responsive routes and proof viewing',{skip:!enabled},async()=>{for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){const context=await browser.newContext({viewport});const page=await context.newPage(),consoleErrors=[],failed=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('requestfailed',r=>failed.push(r.url()));await browserLogin(page,emails.finance1);consoleErrors.length=0;failed.length=0;const csrfReady=page.waitForResponse(response=>response.url().endsWith('/api/v1/auth/csrf')&&response.ok());await page.goto(`${web}/finance/bank-transfers/?api=local`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await csrfReady;const body=(await page.locator('body').innerText()).slice(0,1200);assert.equal(await page.getByRole('heading',{name:'Review Queue'}).isVisible(),true,`queue heading; URL=${page.url()}; body=${body}`);assert.equal(await page.getByText('ZAR 12,500.00').first().isVisible(),true,'paired amount');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`overflow ${viewport.width}`);assert.deepEqual(consoleErrors,[],'console errors');assert.deepEqual(failed,[],'network failures');await context.close();}
  const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();await browserLogin(page,emails.finance1);for(const name of ['pdf','jpeg','png']){await page.goto(`${web}/finance/bank-transfers/details/?api=local&id=${cases[name].id}`,{waitUntil:'domcontentloaded'});await waitForApplicationReady(page);await page.getByRole('button',{name:'Securely view proof'}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();const media=name==='pdf'?dialog.locator('iframe'):dialog.locator('img');assert.match(await media.getAttribute('src'),/^blob:/);await page.getByRole('button',{name:'Close proof viewer'}).click();}const stored=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}));assert.doesNotMatch(stored,/accepted\.(pdf|jpg|png)|%PDF|accessToken|refreshToken/);await context.close();
  const customer=await browser.newContext(),customerPage=await customer.newPage();await browserLogin(customerPage,emails.customerA);await customerPage.goto(`${web}/finance/?api=local`);await waitForApplicationReady(customerPage);await customerPage.waitForURL(/\/dashboard\//);assert.equal(await customerPage.getByText('Finance Overview',{exact:true}).count(),0);await customer.close();
});

test('real assignment conflict, unassignment, review start, comments and role denials',{skip:!enabled},async()=>{const [one,two]=await Promise.all([mutate(actors.finance1,cases.approve.id,'assign',{reviewerId:actors.finance1.user.id},'assign-race-1'),mutate(actors.finance2,cases.approve.id,'assign',{reviewerId:actors.finance2.user.id},'assign-race-2')]);assert.deepEqual([one.response.status,two.response.status].sort(),[200,409]);const authoritative=(await request(`/api/v1/bank-transfer/reviews/${cases.approve.id}`,{token:actors.finance1.token})).data;const owner=authoritative.reviewerId===actors.finance1.user.id?actors.finance1:actors.finance2;const start=await mutate(owner,cases.approve.id,'review',{reviewerId:owner.user.id},'start-approve');assert.equal(start.response.status,200);const comment=await mutate(owner,cases.approve.id,'comments',{comment:'<img src=x onerror=alert(1)> internal'},'comment-approve');assert.equal(comment.response.status,200);assert.equal((await mutate(owner,cases.approve.id,'comments',{comment:'   '},'comment-blank')).response.status,400);assert.equal((await mutate(owner,cases.approve.id,'comments',{comment:'x'.repeat(2001)},'comment-long')).response.status,400);assert.equal((await mutate(actors.consultant,cases.approve.id,'comments',{comment:'denied'},'consultant-comment')).response.status,403);assert.equal((await mutate(actors.customerA,cases.approve.id,'assign',{reviewerId:actors.finance1.user.id},'customer-assign')).response.status,403);assert.equal(sql(`select count(*) from finance_review_comments where review_case_id='${cases.approve.id}' and comment like '<img%'`),'1');
  const unassign=await mutate(actors.finance1,cases.unassigned.id,'assign',{reviewerId:actors.finance1.user.id},'assign-unassign');assert.equal(unassign.response.status,200);const removed=await mutate(actors.finance1,cases.unassigned.id,'assignment',undefined,'unassign-real','DELETE');assert.equal(removed.response.status,200);assert.equal(removed.data.reviewerId,null);
});

test('real approval/rejection idempotency, lifecycle, ownership and database non-mutation',{skip:!enabled},async()=>{const before=sql("select (select count(*) from financial_payments),(select count(*) from financial_receipts),(select count(*) from financial_payment_allocations),(select count(*) from financial_ledger_entries),(select count(*) from bookings where status<>'PENDING')");const owner=(await request(`/api/v1/bank-transfer/reviews/${cases.approve.id}`,{token:actors.finance1.token})).data.reviewerId===actors.finance1.user.id?actors.finance1:actors.finance2;const body={reason:'Cleared funds independently verified'};const approved=await mutate(owner,cases.approve.id,'approve',body,'approve-stable');assert.equal(approved.response.status,200);const replay=await mutate(owner,cases.approve.id,'approve',body,'approve-stable');assert.equal(replay.response.status,200);assert.equal(replay.data.id,approved.data.id);assert.equal((await mutate(owner,cases.approve.id,'approve',{reason:'changed'},'approve-stable')).response.status,409);
  assert.equal((await mutate(actors.finance1,cases.reject.id,'assign',{reviewerId:actors.finance1.user.id},'assign-reject')).response.status,200);assert.equal((await mutate(actors.finance1,cases.reject.id,'review',{reviewerId:actors.finance1.user.id},'start-reject')).response.status,200);const rejected=await mutate(actors.finance1,cases.reject.id,'reject',{reason:'Reference did not match'},'reject-stable');assert.equal(rejected.response.status,200);assert.equal((await mutate(actors.finance1,cases.reject.id,'reject',{reason:'Reference did not match'},'reject-stable')).response.status,200);assert.equal((await mutate(actors.finance1,cases.reject.id,'approve',{reason:'late approval'},'approve-after-reject')).response.status,422);
  assert.equal((await request(`/api/v1/bank-transfer/reviews/${cases.pdf.id}`,{token:actors.customerB.token})).response.status,403);assert.equal((await request(`/api/v1/bank-transfer/reviews/${cases.pdf.id}/proofs/${proofs.pdf.id}`,{token:actors.customerB.token})).response.status,403);assert.equal((await request('/api/v1/bank-transfer/reviews/not-a-uuid',{token:actors.finance1.token})).response.status,400);assert.equal((await request('/api/v1/bank-transfer/reviews',{token:`${actors.finance1.token.slice(0,-1)}x`})).response.status,401);assert.equal((await request('/api/v1/bank-transfer/reviews')).response.status,401);
  const effects=sql(`select (select count(*) from bank_transfer_audit where review_case_id='${cases.approve.id}' and action='APPROVE'),(select count(*) from bank_transfer_outbox where aggregate_id='${cases.approve.id}' and event_type='ReviewApproved'),(select count(*) from bank_transfer_audit where review_case_id='${cases.reject.id}' and action='REJECT'),(select count(*) from bank_transfer_outbox where aggregate_id='${cases.reject.id}' and event_type='ReviewRejected')`);assert.equal(effects,'1|1|1|1');assert.equal(sql("select (select count(*) from financial_payments),(select count(*) from financial_receipts),(select count(*) from financial_payment_allocations),(select count(*) from financial_ledger_entries),(select count(*) from bookings where status<>'PENDING')"),before);
});

test('real concurrent terminal decision converges once and Flyway/proof storage remain consistent',{skip:!enabled},async()=>{assert.equal((await mutate(actors.finance1,cases.concurrent.id,'assign',{reviewerId:actors.finance1.user.id},'assign-concurrent')).response.status,200);assert.equal((await mutate(actors.finance1,cases.concurrent.id,'review',{reviewerId:actors.finance1.user.id},'start-concurrent')).response.status,200);const [approve,reject]=await Promise.all([mutate(actors.finance1,cases.concurrent.id,'approve',{reason:'cleared'},'race-approve'),mutate(actors.finance2,cases.concurrent.id,'reject',{reason:'not cleared'},'race-reject')]);assert.deepEqual([approve.response.status,reject.response.status].sort(),[200,409]);assert.match(sql(`select review_status from bank_transfer_review_cases where id='${cases.concurrent.id}'`),/APPROVED|REJECTED/);assert.equal(sql(`select count(*) from bank_transfer_outbox where aggregate_id='${cases.concurrent.id}' and event_type in ('ReviewApproved','ReviewRejected')`),'1');assert.equal(sql("select string_agg(version,',' order by installed_rank) from flyway_schema_history where success"),'1,2,3,4,5,6,7,8,9,10,11,12,13,14');assert.equal(sql("select count(*) from bank_transfer_proof_documents where status='ACCEPTED' and storage_key is not null"),'7');
});
