import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {launchChromium} from './helpers/playwright-runtime.mjs';
import {enforceOfflineAcceptance,waitForApplicationReady} from './helpers/browser-acceptance.mjs';

const enabled=process.env.RUN_MANUAL_FINANCE_REAL_ACCEPTANCE==='true';
const web=process.env.MANUAL_FINANCE_WEB||'http://localhost:15003';
const api=process.env.MANUAL_FINANCE_API||'http://localhost:8080';
const key=process.env.LOCAL_AUTH_TEST_KEY||'';
const dbEnv={...process.env,PGHOST:process.env.PGHOST||'127.0.0.1',PGPORT:process.env.PGPORT||'55443',PGDATABASE:process.env.PGDATABASE||'vc_rc004',PGUSER:process.env.PGUSER||'vc_rc004',PGPASSWORD:process.env.PGPASSWORD||'vc_rc004_disposable'};
const password='Acceptance-Only-2026!',run=`rc4-${Date.now()}`,email=`${run}@test.invalid`;
const expectedPhone=process.env.MANUAL_FINANCE_EXPECT_PHONE!=='false';
const sql=statement=>execFileSync('psql',['-v','ON_ERROR_STOP=1','-At','-F','|','-c',statement],{env:dbEnv,encoding:'utf8'}).trim();
const eventually=async action=>{const end=Date.now()+15000;let last;while(Date.now()<end){try{return await action();}catch(error){last=error;await new Promise(resolve=>setTimeout(resolve,200));}}throw last;};
async function register(page){await page.goto(`${web}/register/?api=local`);await waitForApplicationReady(page);await page.getByLabel('First name').fill('Manual');await page.getByLabel('Last name').fill('Finance');await page.getByLabel('Email').fill(email);await page.locator('#password').fill(password);await page.locator('#confirmPassword').fill(password);await page.getByLabel(/terms/i).check();await page.getByLabel(/privacy/i).check();await page.getByRole('button',{name:/create account/i}).click();await page.getByText(/check your email/i).waitFor();const token=await eventually(async()=>{const response=await fetch(`${api}/api/v1/auth/development/token?email=${encodeURIComponent(email)}&purpose=VERIFICATION`,{headers:{'X-Local-Test-Key':key}});assert.equal(response.status,200);return (await response.json()).data.token;});await page.goto(`${web}/verify-email/?api=local&token=${encodeURIComponent(token)}`);await waitForApplicationReady(page);await page.goto(`${web}/signin/?api=local`);await waitForApplicationReady(page);await page.getByLabel('Email address').fill(email);await page.locator('#password').fill(password);await Promise.all([page.waitForURL(/account|dashboard/),page.getByRole('button',{name:/sign in/i}).click()]);}

test('manual Finance mode is a non-mutating real customer journey',{skip:!enabled,timeout:120000},async()=>{
 assert.ok(key.length>=24);assert.equal(sql("select current_setting('server_version')||'|'||current_setting('server_encoding')||'|'||current_setting('TimeZone')"),'18.4|UTF8|UTC');assert.equal(sql("select string_agg(version,',' order by installed_rank) from flyway_schema_history where success"),'1,2,3,4,5,6,7,8,9,10,11,12,13,14');
 const browser=await launchChromium({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'});await enforceOfflineAcceptance(context,{allowedOrigins:[new URL(web).origin,new URL(api).origin]});const page=await context.newPage(),errors=[],failed=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('requestfailed',request=>failed.push(new URL(request.url()).origin+new URL(request.url()).pathname));
 try{await register(page);const customerId=sql(`select customer_id from user_accounts where normalized_email='${email}'`),accountId=sql(`select id from financial_accounts where customer_id='${customerId}' and currency='ZAR'`),quoteId=crypto.randomUUID(),bookingId=crypto.randomUUID(),invoiceId=crypto.randomUUID(),reference=`VC-RC4-${run}`.toUpperCase();sql(`insert into quotes(id,quote_number,customer_id,status,traveller_count,total_amount,currency,created_at,updated_at,created_by,updated_by,version) values('${quoteId}','Q-${run}','${customerId}','ACCEPTED',1,10000,'ZAR',now(),now(),'acceptance','acceptance',0);insert into bookings(id,quote_id,customer_id,booking_reference,idempotency_key,status,quoted_amount,currency,created_at,updated_at,created_by,updated_by,version) values('${bookingId}','${quoteId}','${customerId}','${reference}','${run}','DEPOSIT_PENDING',10000,'ZAR',now(),now(),'acceptance','acceptance',0);insert into booking_payment_summary(id,booking_id,quoted_amount,deposit_due,deposit_paid,balance_due,balance_paid,currency,payment_status,created_at,updated_at,created_by,updated_by,version) values('${crypto.randomUUID()}','${bookingId}',10000,10000,0,0,0,'ZAR','DEPOSIT_PENDING',now(),now(),'acceptance','acceptance',0);insert into financial_invoices(id,invoice_number,account_id,customer_id,booking_reference,currency,status,allocated_amount,credited_amount,version,created_at,updated_at,created_by,updated_by) values('${invoiceId}','INV-${run}','${accountId}','${customerId}','${reference}','ZAR','ISSUED',0,0,0,now(),now(),'acceptance','acceptance');insert into financial_invoice_lines(invoice_id,position,description,quantity,unit_price,tax_rate) values('${invoiceId}',0,'RC-004 manual launch',1,10000,0);`);
 const before=sql(`select (select count(*) from bank_transfer_review_cases where customer_id='${customerId}'),(select count(*) from financial_payments where customer_id='${customerId}'),(select count(*) from financial_receipts where customer_id='${customerId}'),(select count(*) from booking_status_history where booking_id='${bookingId}'),(select count(*) from notification_intents where recipient_id='${customerId}' and notification_type in('PAYMENT_RECORDED','RECEIPT_ISSUED','BOOKING_CONFIRMED'))`);
 for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:390,height:844}]){await page.setViewportSize(viewport);await page.goto(`${web}/bank-transfer/?api=local`);await waitForApplicationReady(page);const body=await page.locator('body').innerText();assert.match(body,/Manual Finance Assistance/i);assert.match(body,new RegExp(`INV-${run}`,'i'));assert.match(body,/ZAR/);assert.match(body,/No payment has been recorded/);assert.doesNotMatch(body,/Acceptance Bank|123456789|Create review case|Upload proof|Proof received/);assert.equal(await page.locator('a[href^="tel:"]').count(),expectedPhone?1:0);assert.equal(await page.locator('a[href^="mailto:"]').count(),1);assert.equal(await page.getByRole('button',{name:'Copy reference'}).isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}
 const login=await fetch(`${api}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,deviceName:'RC-004'})}).then(r=>r.json()),access=login.data.accessToken;const response=await fetch(`${api}/api/v1/bank-transfer/reviews`,{method:'POST',headers:{Authorization:`Bearer ${access}`,Accept:'application/problem+json','Content-Type':'application/json','Idempotency-Key':'rc4-blocked'},body:JSON.stringify({bookingId,invoiceId,currency:'ZAR',amount:10000,bankAccount:'must-not-persist',transferReference:'BLOCKED'})});const create={status:response.status,body:await response.json()};assert.equal(create.status,409);assert.equal(create.body.code,'BANK_TRANSFER_SELF_SERVICE_UNAVAILABLE');assert.doesNotMatch(JSON.stringify(create.body),/class|sql|configuration|storage/i);
 assert.equal(sql(`select (select count(*) from bank_transfer_review_cases where customer_id='${customerId}'),(select count(*) from financial_payments where customer_id='${customerId}'),(select count(*) from financial_receipts where customer_id='${customerId}'),(select count(*) from booking_status_history where booking_id='${bookingId}'),(select count(*) from notification_intents where recipient_id='${customerId}' and notification_type in('PAYMENT_RECORDED','RECEIPT_ISSUED','BOOKING_CONFIRMED'))`),before);assert.equal(sql(`select status from bookings where id='${bookingId}'`),'DEPOSIT_PENDING');assert.deepEqual(errors,[]);assert.ok(failed.every(path=>[`${api}/api/v1/auth/session`,`${api}/api/v1/auth/email-verification/confirm`,`${api}/api/v1/packages`,`${api}/api/v1/packages/featured`,`${web}/images/favicon.png`].includes(path)),JSON.stringify(failed));await page.getByRole('button',{name:'Logout'}).click();await page.goto(`${web}/bank-transfer/?api=local`);await waitForApplicationReady(page);assert.match(page.url(),/signin/);assert.doesNotMatch(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}})),/accessToken|refreshToken|INV-|financial_invoices/i);
 }finally{await context.close();await browser.close();}
});
